/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-03-29")
public class BoletaCategoria implements org.apache.thrift.TBase<BoletaCategoria, BoletaCategoria._Fields>, java.io.Serializable, Cloneable, Comparable<BoletaCategoria> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BoletaCategoria");

  private static final org.apache.thrift.protocol.TField BOLETA_FIELD_DESC = new org.apache.thrift.protocol.TField("boleta", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CATEGORIA_FIELD_DESC = new org.apache.thrift.protocol.TField("categoria", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BoletaCategoriaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BoletaCategoriaTupleSchemeFactory();

  public BoletaID boleta; // required
  public CategoriaID categoria; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BOLETA((short)1, "boleta"),
    CATEGORIA((short)2, "categoria");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BOLETA
          return BOLETA;
        case 2: // CATEGORIA
          return CATEGORIA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BOLETA, new org.apache.thrift.meta_data.FieldMetaData("boleta", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BoletaID.class)));
    tmpMap.put(_Fields.CATEGORIA, new org.apache.thrift.meta_data.FieldMetaData("categoria", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CategoriaID.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BoletaCategoria.class, metaDataMap);
  }

  public BoletaCategoria() {
  }

  public BoletaCategoria(
    BoletaID boleta,
    CategoriaID categoria)
  {
    this();
    this.boleta = boleta;
    this.categoria = categoria;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BoletaCategoria(BoletaCategoria other) {
    if (other.isSetBoleta()) {
      this.boleta = new BoletaID(other.boleta);
    }
    if (other.isSetCategoria()) {
      this.categoria = new CategoriaID(other.categoria);
    }
  }

  public BoletaCategoria deepCopy() {
    return new BoletaCategoria(this);
  }

  @Override
  public void clear() {
    this.boleta = null;
    this.categoria = null;
  }

  public BoletaID getBoleta() {
    return this.boleta;
  }

  public BoletaCategoria setBoleta(BoletaID boleta) {
    this.boleta = boleta;
    return this;
  }

  public void unsetBoleta() {
    this.boleta = null;
  }

  /** Returns true if field boleta is set (has been assigned a value) and false otherwise */
  public boolean isSetBoleta() {
    return this.boleta != null;
  }

  public void setBoletaIsSet(boolean value) {
    if (!value) {
      this.boleta = null;
    }
  }

  public CategoriaID getCategoria() {
    return this.categoria;
  }

  public BoletaCategoria setCategoria(CategoriaID categoria) {
    this.categoria = categoria;
    return this;
  }

  public void unsetCategoria() {
    this.categoria = null;
  }

  /** Returns true if field categoria is set (has been assigned a value) and false otherwise */
  public boolean isSetCategoria() {
    return this.categoria != null;
  }

  public void setCategoriaIsSet(boolean value) {
    if (!value) {
      this.categoria = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case BOLETA:
      if (value == null) {
        unsetBoleta();
      } else {
        setBoleta((BoletaID)value);
      }
      break;

    case CATEGORIA:
      if (value == null) {
        unsetCategoria();
      } else {
        setCategoria((CategoriaID)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case BOLETA:
      return getBoleta();

    case CATEGORIA:
      return getCategoria();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case BOLETA:
      return isSetBoleta();
    case CATEGORIA:
      return isSetCategoria();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BoletaCategoria)
      return this.equals((BoletaCategoria)that);
    return false;
  }

  public boolean equals(BoletaCategoria that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_boleta = true && this.isSetBoleta();
    boolean that_present_boleta = true && that.isSetBoleta();
    if (this_present_boleta || that_present_boleta) {
      if (!(this_present_boleta && that_present_boleta))
        return false;
      if (!this.boleta.equals(that.boleta))
        return false;
    }

    boolean this_present_categoria = true && this.isSetCategoria();
    boolean that_present_categoria = true && that.isSetCategoria();
    if (this_present_categoria || that_present_categoria) {
      if (!(this_present_categoria && that_present_categoria))
        return false;
      if (!this.categoria.equals(that.categoria))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetBoleta()) ? 131071 : 524287);
    if (isSetBoleta())
      hashCode = hashCode * 8191 + boleta.hashCode();

    hashCode = hashCode * 8191 + ((isSetCategoria()) ? 131071 : 524287);
    if (isSetCategoria())
      hashCode = hashCode * 8191 + categoria.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BoletaCategoria other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetBoleta()).compareTo(other.isSetBoleta());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBoleta()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.boleta, other.boleta);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCategoria()).compareTo(other.isSetCategoria());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCategoria()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.categoria, other.categoria);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BoletaCategoria(");
    boolean first = true;

    sb.append("boleta:");
    if (this.boleta == null) {
      sb.append("null");
    } else {
      sb.append(this.boleta);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("categoria:");
    if (this.categoria == null) {
      sb.append("null");
    } else {
      sb.append(this.categoria);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (boleta == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'boleta' was not present! Struct: " + toString());
    }
    if (categoria == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'categoria' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BoletaCategoriaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BoletaCategoriaStandardScheme getScheme() {
      return new BoletaCategoriaStandardScheme();
    }
  }

  private static class BoletaCategoriaStandardScheme extends org.apache.thrift.scheme.StandardScheme<BoletaCategoria> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BoletaCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BOLETA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.boleta = new BoletaID();
              struct.boleta.read(iprot);
              struct.setBoletaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CATEGORIA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.categoria = new CategoriaID();
              struct.categoria.read(iprot);
              struct.setCategoriaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BoletaCategoria struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.boleta != null) {
        oprot.writeFieldBegin(BOLETA_FIELD_DESC);
        struct.boleta.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.categoria != null) {
        oprot.writeFieldBegin(CATEGORIA_FIELD_DESC);
        struct.categoria.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BoletaCategoriaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BoletaCategoriaTupleScheme getScheme() {
      return new BoletaCategoriaTupleScheme();
    }
  }

  private static class BoletaCategoriaTupleScheme extends org.apache.thrift.scheme.TupleScheme<BoletaCategoria> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BoletaCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.boleta.write(oprot);
      struct.categoria.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BoletaCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.boleta = new BoletaID();
      struct.boleta.read(iprot);
      struct.setBoletaIsSet(true);
      struct.categoria = new CategoriaID();
      struct.categoria.read(iprot);
      struct.setCategoriaIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

