/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-03-29")
public class ProductoCategoria implements org.apache.thrift.TBase<ProductoCategoria, ProductoCategoria._Fields>, java.io.Serializable, Cloneable, Comparable<ProductoCategoria> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProductoCategoria");

  private static final org.apache.thrift.protocol.TField PRODUCTO_FIELD_DESC = new org.apache.thrift.protocol.TField("producto", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CATEGORIA_FIELD_DESC = new org.apache.thrift.protocol.TField("categoria", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ProductoCategoriaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ProductoCategoriaTupleSchemeFactory();

  public ProductoID producto; // required
  public CategoriaID categoria; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRODUCTO((short)1, "producto"),
    CATEGORIA((short)2, "categoria");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRODUCTO
          return PRODUCTO;
        case 2: // CATEGORIA
          return CATEGORIA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRODUCTO, new org.apache.thrift.meta_data.FieldMetaData("producto", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ProductoID.class)));
    tmpMap.put(_Fields.CATEGORIA, new org.apache.thrift.meta_data.FieldMetaData("categoria", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CategoriaID.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProductoCategoria.class, metaDataMap);
  }

  public ProductoCategoria() {
  }

  public ProductoCategoria(
    ProductoID producto,
    CategoriaID categoria)
  {
    this();
    this.producto = producto;
    this.categoria = categoria;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProductoCategoria(ProductoCategoria other) {
    if (other.isSetProducto()) {
      this.producto = new ProductoID(other.producto);
    }
    if (other.isSetCategoria()) {
      this.categoria = new CategoriaID(other.categoria);
    }
  }

  public ProductoCategoria deepCopy() {
    return new ProductoCategoria(this);
  }

  @Override
  public void clear() {
    this.producto = null;
    this.categoria = null;
  }

  public ProductoID getProducto() {
    return this.producto;
  }

  public ProductoCategoria setProducto(ProductoID producto) {
    this.producto = producto;
    return this;
  }

  public void unsetProducto() {
    this.producto = null;
  }

  /** Returns true if field producto is set (has been assigned a value) and false otherwise */
  public boolean isSetProducto() {
    return this.producto != null;
  }

  public void setProductoIsSet(boolean value) {
    if (!value) {
      this.producto = null;
    }
  }

  public CategoriaID getCategoria() {
    return this.categoria;
  }

  public ProductoCategoria setCategoria(CategoriaID categoria) {
    this.categoria = categoria;
    return this;
  }

  public void unsetCategoria() {
    this.categoria = null;
  }

  /** Returns true if field categoria is set (has been assigned a value) and false otherwise */
  public boolean isSetCategoria() {
    return this.categoria != null;
  }

  public void setCategoriaIsSet(boolean value) {
    if (!value) {
      this.categoria = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PRODUCTO:
      if (value == null) {
        unsetProducto();
      } else {
        setProducto((ProductoID)value);
      }
      break;

    case CATEGORIA:
      if (value == null) {
        unsetCategoria();
      } else {
        setCategoria((CategoriaID)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PRODUCTO:
      return getProducto();

    case CATEGORIA:
      return getCategoria();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PRODUCTO:
      return isSetProducto();
    case CATEGORIA:
      return isSetCategoria();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ProductoCategoria)
      return this.equals((ProductoCategoria)that);
    return false;
  }

  public boolean equals(ProductoCategoria that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_producto = true && this.isSetProducto();
    boolean that_present_producto = true && that.isSetProducto();
    if (this_present_producto || that_present_producto) {
      if (!(this_present_producto && that_present_producto))
        return false;
      if (!this.producto.equals(that.producto))
        return false;
    }

    boolean this_present_categoria = true && this.isSetCategoria();
    boolean that_present_categoria = true && that.isSetCategoria();
    if (this_present_categoria || that_present_categoria) {
      if (!(this_present_categoria && that_present_categoria))
        return false;
      if (!this.categoria.equals(that.categoria))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetProducto()) ? 131071 : 524287);
    if (isSetProducto())
      hashCode = hashCode * 8191 + producto.hashCode();

    hashCode = hashCode * 8191 + ((isSetCategoria()) ? 131071 : 524287);
    if (isSetCategoria())
      hashCode = hashCode * 8191 + categoria.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ProductoCategoria other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetProducto()).compareTo(other.isSetProducto());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProducto()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.producto, other.producto);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCategoria()).compareTo(other.isSetCategoria());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCategoria()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.categoria, other.categoria);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ProductoCategoria(");
    boolean first = true;

    sb.append("producto:");
    if (this.producto == null) {
      sb.append("null");
    } else {
      sb.append(this.producto);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("categoria:");
    if (this.categoria == null) {
      sb.append("null");
    } else {
      sb.append(this.categoria);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (producto == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'producto' was not present! Struct: " + toString());
    }
    if (categoria == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'categoria' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProductoCategoriaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProductoCategoriaStandardScheme getScheme() {
      return new ProductoCategoriaStandardScheme();
    }
  }

  private static class ProductoCategoriaStandardScheme extends org.apache.thrift.scheme.StandardScheme<ProductoCategoria> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProductoCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRODUCTO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.producto = new ProductoID();
              struct.producto.read(iprot);
              struct.setProductoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CATEGORIA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.categoria = new CategoriaID();
              struct.categoria.read(iprot);
              struct.setCategoriaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProductoCategoria struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.producto != null) {
        oprot.writeFieldBegin(PRODUCTO_FIELD_DESC);
        struct.producto.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.categoria != null) {
        oprot.writeFieldBegin(CATEGORIA_FIELD_DESC);
        struct.categoria.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProductoCategoriaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProductoCategoriaTupleScheme getScheme() {
      return new ProductoCategoriaTupleScheme();
    }
  }

  private static class ProductoCategoriaTupleScheme extends org.apache.thrift.scheme.TupleScheme<ProductoCategoria> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProductoCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.producto.write(oprot);
      struct.categoria.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProductoCategoria struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.producto = new ProductoID();
      struct.producto.read(iprot);
      struct.setProductoIsSet(true);
      struct.categoria = new CategoriaID();
      struct.categoria.read(iprot);
      struct.setCategoriaIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

