/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ProductoPropertyValue extends org.apache.thrift.TUnion<ProductoPropertyValue, ProductoPropertyValue._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProductoPropertyValue");
  private static final org.apache.thrift.protocol.TField LONG_DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("longDescription", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SALE_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("salePrice", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField UPC_FIELD_DESC = new org.apache.thrift.protocol.TField("upc", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LONG_DESCRIPTION((short)1, "longDescription"),
    SALE_PRICE((short)2, "salePrice"),
    UPC((short)3, "upc"),
    NAME((short)4, "name");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LONG_DESCRIPTION
          return LONG_DESCRIPTION;
        case 2: // SALE_PRICE
          return SALE_PRICE;
        case 3: // UPC
          return UPC;
        case 4: // NAME
          return NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LONG_DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("longDescription", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SALE_PRICE, new org.apache.thrift.meta_data.FieldMetaData("salePrice", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.UPC, new org.apache.thrift.meta_data.FieldMetaData("upc", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProductoPropertyValue.class, metaDataMap);
  }

  public ProductoPropertyValue() {
    super();
  }

  public ProductoPropertyValue(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public ProductoPropertyValue(ProductoPropertyValue other) {
    super(other);
  }
  public ProductoPropertyValue deepCopy() {
    return new ProductoPropertyValue(this);
  }

  public static ProductoPropertyValue longDescription(java.lang.String value) {
    ProductoPropertyValue x = new ProductoPropertyValue();
    x.setLongDescription(value);
    return x;
  }

  public static ProductoPropertyValue salePrice(double value) {
    ProductoPropertyValue x = new ProductoPropertyValue();
    x.setSalePrice(value);
    return x;
  }

  public static ProductoPropertyValue upc(java.lang.String value) {
    ProductoPropertyValue x = new ProductoPropertyValue();
    x.setUpc(value);
    return x;
  }

  public static ProductoPropertyValue name(java.lang.String value) {
    ProductoPropertyValue x = new ProductoPropertyValue();
    x.setName(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case LONG_DESCRIPTION:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'longDescription', but got " + value.getClass().getSimpleName());
      case SALE_PRICE:
        if (value instanceof java.lang.Double) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Double for field 'salePrice', but got " + value.getClass().getSimpleName());
      case UPC:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'upc', but got " + value.getClass().getSimpleName());
      case NAME:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'name', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case LONG_DESCRIPTION:
          if (field.type == LONG_DESCRIPTION_FIELD_DESC.type) {
            java.lang.String longDescription;
            longDescription = iprot.readString();
            return longDescription;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case SALE_PRICE:
          if (field.type == SALE_PRICE_FIELD_DESC.type) {
            java.lang.Double salePrice;
            salePrice = iprot.readDouble();
            return salePrice;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case UPC:
          if (field.type == UPC_FIELD_DESC.type) {
            java.lang.String upc;
            upc = iprot.readString();
            return upc;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case NAME:
          if (field.type == NAME_FIELD_DESC.type) {
            java.lang.String name;
            name = iprot.readString();
            return name;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LONG_DESCRIPTION:
        java.lang.String longDescription = (java.lang.String)value_;
        oprot.writeString(longDescription);
        return;
      case SALE_PRICE:
        java.lang.Double salePrice = (java.lang.Double)value_;
        oprot.writeDouble(salePrice);
        return;
      case UPC:
        java.lang.String upc = (java.lang.String)value_;
        oprot.writeString(upc);
        return;
      case NAME:
        java.lang.String name = (java.lang.String)value_;
        oprot.writeString(name);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case LONG_DESCRIPTION:
          java.lang.String longDescription;
          longDescription = iprot.readString();
          return longDescription;
        case SALE_PRICE:
          java.lang.Double salePrice;
          salePrice = iprot.readDouble();
          return salePrice;
        case UPC:
          java.lang.String upc;
          upc = iprot.readString();
          return upc;
        case NAME:
          java.lang.String name;
          name = iprot.readString();
          return name;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LONG_DESCRIPTION:
        java.lang.String longDescription = (java.lang.String)value_;
        oprot.writeString(longDescription);
        return;
      case SALE_PRICE:
        java.lang.Double salePrice = (java.lang.Double)value_;
        oprot.writeDouble(salePrice);
        return;
      case UPC:
        java.lang.String upc = (java.lang.String)value_;
        oprot.writeString(upc);
        return;
      case NAME:
        java.lang.String name = (java.lang.String)value_;
        oprot.writeString(name);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case LONG_DESCRIPTION:
        return LONG_DESCRIPTION_FIELD_DESC;
      case SALE_PRICE:
        return SALE_PRICE_FIELD_DESC;
      case UPC:
        return UPC_FIELD_DESC;
      case NAME:
        return NAME_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public java.lang.String getLongDescription() {
    if (getSetField() == _Fields.LONG_DESCRIPTION) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'longDescription' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLongDescription(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.LONG_DESCRIPTION;
    value_ = value;
  }

  public double getSalePrice() {
    if (getSetField() == _Fields.SALE_PRICE) {
      return (java.lang.Double)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'salePrice' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setSalePrice(double value) {
    setField_ = _Fields.SALE_PRICE;
    value_ = value;
  }

  public java.lang.String getUpc() {
    if (getSetField() == _Fields.UPC) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'upc' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setUpc(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.UPC;
    value_ = value;
  }

  public java.lang.String getName() {
    if (getSetField() == _Fields.NAME) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'name' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setName(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.NAME;
    value_ = value;
  }

  public boolean isSetLongDescription() {
    return setField_ == _Fields.LONG_DESCRIPTION;
  }


  public boolean isSetSalePrice() {
    return setField_ == _Fields.SALE_PRICE;
  }


  public boolean isSetUpc() {
    return setField_ == _Fields.UPC;
  }


  public boolean isSetName() {
    return setField_ == _Fields.NAME;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof ProductoPropertyValue) {
      return equals((ProductoPropertyValue)other);
    } else {
      return false;
    }
  }

  public boolean equals(ProductoPropertyValue other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(ProductoPropertyValue other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
